//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TermProject.WebS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CloudWebSSoap", Namespace="http://tempuri.org/")]
    public partial class CloudWebS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmUserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignWebServiceAPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAPIKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloudUserStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFilesByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpDateFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectFilesWithIconsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUserTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUserTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFilesByIconOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDuplicateUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoragePlansOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPurchaseExtraStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserStorageCapacityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CloudWebS() {
            this.Url = global::TermProject.Properties.Settings.Default.TermProject_WebS_CloudWebS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event ConfirmUserLoginCompletedEventHandler ConfirmUserLoginCompleted;
        
        /// <remarks/>
        public event AssignWebServiceAPICompletedEventHandler AssignWebServiceAPICompleted;
        
        /// <remarks/>
        public event VerifyAPIKeyCompletedEventHandler VerifyAPIKeyCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event CloudUserStorageCompletedEventHandler CloudUserStorageCompleted;
        
        /// <remarks/>
        public event GetFilesByUserCompletedEventHandler GetFilesByUserCompleted;
        
        /// <remarks/>
        public event DeleteFileCompletedEventHandler DeleteFileCompleted;
        
        /// <remarks/>
        public event UpDateFileCompletedEventHandler UpDateFileCompleted;
        
        /// <remarks/>
        public event GetAllUsersCompletedEventHandler GetAllUsersCompleted;
        
        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;
        
        /// <remarks/>
        public event SelectFilesWithIconsCompletedEventHandler SelectFilesWithIconsCompleted;
        
        /// <remarks/>
        public event InsertUserTransactionsCompletedEventHandler InsertUserTransactionsCompleted;
        
        /// <remarks/>
        public event SelectUserTransactionsCompletedEventHandler SelectUserTransactionsCompleted;
        
        /// <remarks/>
        public event GetFilesByIconCompletedEventHandler GetFilesByIconCompleted;
        
        /// <remarks/>
        public event GetAccountTypeCompletedEventHandler GetAccountTypeCompleted;
        
        /// <remarks/>
        public event CheckDuplicateUsernameCompletedEventHandler CheckDuplicateUsernameCompleted;
        
        /// <remarks/>
        public event GetStoragePlansCompletedEventHandler GetStoragePlansCompleted;
        
        /// <remarks/>
        public event InsertPurchaseExtraStorageCompletedEventHandler InsertPurchaseExtraStorageCompleted;
        
        /// <remarks/>
        public event UpdateUserStorageCapacityCompletedEventHandler UpdateUserStorageCapacityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUser(User newUser) {
            object[] results = this.Invoke("AddUser", new object[] {
                        newUser});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(User newUser) {
            this.AddUserAsync(newUser, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(User newUser, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        newUser}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmUserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ConfirmUserLogin(string Username, string password) {
            object[] results = this.Invoke("ConfirmUserLogin", new object[] {
                        Username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmUserLoginAsync(string Username, string password) {
            this.ConfirmUserLoginAsync(Username, password, null);
        }
        
        /// <remarks/>
        public void ConfirmUserLoginAsync(string Username, string password, object userState) {
            if ((this.ConfirmUserLoginOperationCompleted == null)) {
                this.ConfirmUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmUserLoginOperationCompleted);
            }
            this.InvokeAsync("ConfirmUserLogin", new object[] {
                        Username,
                        password}, this.ConfirmUserLoginOperationCompleted, userState);
        }
        
        private void OnConfirmUserLoginOperationCompleted(object arg) {
            if ((this.ConfirmUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmUserLoginCompleted(this, new ConfirmUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignWebServiceAPI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AssignWebServiceAPI(string userName) {
            object[] results = this.Invoke("AssignWebServiceAPI", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AssignWebServiceAPIAsync(string userName) {
            this.AssignWebServiceAPIAsync(userName, null);
        }
        
        /// <remarks/>
        public void AssignWebServiceAPIAsync(string userName, object userState) {
            if ((this.AssignWebServiceAPIOperationCompleted == null)) {
                this.AssignWebServiceAPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignWebServiceAPIOperationCompleted);
            }
            this.InvokeAsync("AssignWebServiceAPI", new object[] {
                        userName}, this.AssignWebServiceAPIOperationCompleted, userState);
        }
        
        private void OnAssignWebServiceAPIOperationCompleted(object arg) {
            if ((this.AssignWebServiceAPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignWebServiceAPICompleted(this, new AssignWebServiceAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyAPIKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyAPIKey(string APIKey) {
            object[] results = this.Invoke("VerifyAPIKey", new object[] {
                        APIKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAPIKeyAsync(string APIKey) {
            this.VerifyAPIKeyAsync(APIKey, null);
        }
        
        /// <remarks/>
        public void VerifyAPIKeyAsync(string APIKey, object userState) {
            if ((this.VerifyAPIKeyOperationCompleted == null)) {
                this.VerifyAPIKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAPIKeyOperationCompleted);
            }
            this.InvokeAsync("VerifyAPIKey", new object[] {
                        APIKey}, this.VerifyAPIKeyOperationCompleted, userState);
        }
        
        private void OnVerifyAPIKeyOperationCompleted(object arg) {
            if ((this.VerifyAPIKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAPIKeyCompleted(this, new VerifyAPIKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadFile(string API_Key, FileInfoWS OBJFile, string username) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        API_Key,
                        OBJFile,
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(string API_Key, FileInfoWS OBJFile, string username) {
            this.UploadFileAsync(API_Key, OBJFile, username, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(string API_Key, FileInfoWS OBJFile, string username, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        API_Key,
                        OBJFile,
                        username}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloudUserStorage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CloudUserStorage() {
            object[] results = this.Invoke("CloudUserStorage", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CloudUserStorageAsync() {
            this.CloudUserStorageAsync(null);
        }
        
        /// <remarks/>
        public void CloudUserStorageAsync(object userState) {
            if ((this.CloudUserStorageOperationCompleted == null)) {
                this.CloudUserStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloudUserStorageOperationCompleted);
            }
            this.InvokeAsync("CloudUserStorage", new object[0], this.CloudUserStorageOperationCompleted, userState);
        }
        
        private void OnCloudUserStorageOperationCompleted(object arg) {
            if ((this.CloudUserStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloudUserStorageCompleted(this, new CloudUserStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFilesByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFilesByUser(string userName) {
            object[] results = this.Invoke("GetFilesByUser", new object[] {
                        userName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFilesByUserAsync(string userName) {
            this.GetFilesByUserAsync(userName, null);
        }
        
        /// <remarks/>
        public void GetFilesByUserAsync(string userName, object userState) {
            if ((this.GetFilesByUserOperationCompleted == null)) {
                this.GetFilesByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFilesByUserOperationCompleted);
            }
            this.InvokeAsync("GetFilesByUser", new object[] {
                        userName}, this.GetFilesByUserOperationCompleted, userState);
        }
        
        private void OnGetFilesByUserOperationCompleted(object arg) {
            if ((this.GetFilesByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFilesByUserCompleted(this, new GetFilesByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteFile(string username, string fileName, float size) {
            object[] results = this.Invoke("DeleteFile", new object[] {
                        username,
                        fileName,
                        size});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileAsync(string username, string fileName, float size) {
            this.DeleteFileAsync(username, fileName, size, null);
        }
        
        /// <remarks/>
        public void DeleteFileAsync(string username, string fileName, float size, object userState) {
            if ((this.DeleteFileOperationCompleted == null)) {
                this.DeleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileOperationCompleted);
            }
            this.InvokeAsync("DeleteFile", new object[] {
                        username,
                        fileName,
                        size}, this.DeleteFileOperationCompleted, userState);
        }
        
        private void OnDeleteFileOperationCompleted(object arg) {
            if ((this.DeleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileCompleted(this, new DeleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpDateFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpDateFile(FileInfoWS OBJFile) {
            object[] results = this.Invoke("UpDateFile", new object[] {
                        OBJFile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpDateFileAsync(FileInfoWS OBJFile) {
            this.UpDateFileAsync(OBJFile, null);
        }
        
        /// <remarks/>
        public void UpDateFileAsync(FileInfoWS OBJFile, object userState) {
            if ((this.UpDateFileOperationCompleted == null)) {
                this.UpDateFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpDateFileOperationCompleted);
            }
            this.InvokeAsync("UpDateFile", new object[] {
                        OBJFile}, this.UpDateFileOperationCompleted, userState);
        }
        
        private void OnUpDateFileOperationCompleted(object arg) {
            if ((this.UpDateFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpDateFileCompleted(this, new UpDateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUsers() {
            object[] results = this.Invoke("GetAllUsers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUsersAsync() {
            this.GetAllUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUsersAsync(object userState) {
            if ((this.GetAllUsersOperationCompleted == null)) {
                this.GetAllUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUsersOperationCompleted);
            }
            this.InvokeAsync("GetAllUsers", new object[0], this.GetAllUsersOperationCompleted, userState);
        }
        
        private void OnGetAllUsersOperationCompleted(object arg) {
            if ((this.GetAllUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUsersCompleted(this, new GetAllUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUser(string username) {
            this.Invoke("DeleteUser", new object[] {
                        username});
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string username) {
            this.DeleteUserAsync(username, null);
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string username, object userState) {
            if ((this.DeleteUserOperationCompleted == null)) {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                        username}, this.DeleteUserOperationCompleted, userState);
        }
        
        private void OnDeleteUserOperationCompleted(object arg) {
            if ((this.DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectFilesWithIcons", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SelectFilesWithIcons(string userName) {
            object[] results = this.Invoke("SelectFilesWithIcons", new object[] {
                        userName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SelectFilesWithIconsAsync(string userName) {
            this.SelectFilesWithIconsAsync(userName, null);
        }
        
        /// <remarks/>
        public void SelectFilesWithIconsAsync(string userName, object userState) {
            if ((this.SelectFilesWithIconsOperationCompleted == null)) {
                this.SelectFilesWithIconsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectFilesWithIconsOperationCompleted);
            }
            this.InvokeAsync("SelectFilesWithIcons", new object[] {
                        userName}, this.SelectFilesWithIconsOperationCompleted, userState);
        }
        
        private void OnSelectFilesWithIconsOperationCompleted(object arg) {
            if ((this.SelectFilesWithIconsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectFilesWithIconsCompleted(this, new SelectFilesWithIconsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUserTransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUserTransactions(string Username, string Desc, string date) {
            object[] results = this.Invoke("InsertUserTransactions", new object[] {
                        Username,
                        Desc,
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertUserTransactionsAsync(string Username, string Desc, string date) {
            this.InsertUserTransactionsAsync(Username, Desc, date, null);
        }
        
        /// <remarks/>
        public void InsertUserTransactionsAsync(string Username, string Desc, string date, object userState) {
            if ((this.InsertUserTransactionsOperationCompleted == null)) {
                this.InsertUserTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUserTransactionsOperationCompleted);
            }
            this.InvokeAsync("InsertUserTransactions", new object[] {
                        Username,
                        Desc,
                        date}, this.InsertUserTransactionsOperationCompleted, userState);
        }
        
        private void OnInsertUserTransactionsOperationCompleted(object arg) {
            if ((this.InsertUserTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUserTransactionsCompleted(this, new InsertUserTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectUserTransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SelectUserTransactions(string Username) {
            object[] results = this.Invoke("SelectUserTransactions", new object[] {
                        Username});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SelectUserTransactionsAsync(string Username) {
            this.SelectUserTransactionsAsync(Username, null);
        }
        
        /// <remarks/>
        public void SelectUserTransactionsAsync(string Username, object userState) {
            if ((this.SelectUserTransactionsOperationCompleted == null)) {
                this.SelectUserTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUserTransactionsOperationCompleted);
            }
            this.InvokeAsync("SelectUserTransactions", new object[] {
                        Username}, this.SelectUserTransactionsOperationCompleted, userState);
        }
        
        private void OnSelectUserTransactionsOperationCompleted(object arg) {
            if ((this.SelectUserTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUserTransactionsCompleted(this, new SelectUserTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFilesByIcon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFilesByIcon(string userName) {
            object[] results = this.Invoke("GetFilesByIcon", new object[] {
                        userName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFilesByIconAsync(string userName) {
            this.GetFilesByIconAsync(userName, null);
        }
        
        /// <remarks/>
        public void GetFilesByIconAsync(string userName, object userState) {
            if ((this.GetFilesByIconOperationCompleted == null)) {
                this.GetFilesByIconOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFilesByIconOperationCompleted);
            }
            this.InvokeAsync("GetFilesByIcon", new object[] {
                        userName}, this.GetFilesByIconOperationCompleted, userState);
        }
        
        private void OnGetFilesByIconOperationCompleted(object arg) {
            if ((this.GetFilesByIconCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFilesByIconCompleted(this, new GetFilesByIconCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountType(string username) {
            object[] results = this.Invoke("GetAccountType", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountTypeAsync(string username) {
            this.GetAccountTypeAsync(username, null);
        }
        
        /// <remarks/>
        public void GetAccountTypeAsync(string username, object userState) {
            if ((this.GetAccountTypeOperationCompleted == null)) {
                this.GetAccountTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountTypeOperationCompleted);
            }
            this.InvokeAsync("GetAccountType", new object[] {
                        username}, this.GetAccountTypeOperationCompleted, userState);
        }
        
        private void OnGetAccountTypeOperationCompleted(object arg) {
            if ((this.GetAccountTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountTypeCompleted(this, new GetAccountTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDuplicateUsername", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckDuplicateUsername(string username) {
            object[] results = this.Invoke("CheckDuplicateUsername", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDuplicateUsernameAsync(string username) {
            this.CheckDuplicateUsernameAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckDuplicateUsernameAsync(string username, object userState) {
            if ((this.CheckDuplicateUsernameOperationCompleted == null)) {
                this.CheckDuplicateUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDuplicateUsernameOperationCompleted);
            }
            this.InvokeAsync("CheckDuplicateUsername", new object[] {
                        username}, this.CheckDuplicateUsernameOperationCompleted, userState);
        }
        
        private void OnCheckDuplicateUsernameOperationCompleted(object arg) {
            if ((this.CheckDuplicateUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDuplicateUsernameCompleted(this, new CheckDuplicateUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoragePlans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStoragePlans() {
            object[] results = this.Invoke("GetStoragePlans", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoragePlansAsync() {
            this.GetStoragePlansAsync(null);
        }
        
        /// <remarks/>
        public void GetStoragePlansAsync(object userState) {
            if ((this.GetStoragePlansOperationCompleted == null)) {
                this.GetStoragePlansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoragePlansOperationCompleted);
            }
            this.InvokeAsync("GetStoragePlans", new object[0], this.GetStoragePlansOperationCompleted, userState);
        }
        
        private void OnGetStoragePlansOperationCompleted(object arg) {
            if ((this.GetStoragePlansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoragePlansCompleted(this, new GetStoragePlansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertPurchaseExtraStorage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertPurchaseExtraStorage(ExtraStorageUser ESU) {
            object[] results = this.Invoke("InsertPurchaseExtraStorage", new object[] {
                        ESU});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPurchaseExtraStorageAsync(ExtraStorageUser ESU) {
            this.InsertPurchaseExtraStorageAsync(ESU, null);
        }
        
        /// <remarks/>
        public void InsertPurchaseExtraStorageAsync(ExtraStorageUser ESU, object userState) {
            if ((this.InsertPurchaseExtraStorageOperationCompleted == null)) {
                this.InsertPurchaseExtraStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPurchaseExtraStorageOperationCompleted);
            }
            this.InvokeAsync("InsertPurchaseExtraStorage", new object[] {
                        ESU}, this.InsertPurchaseExtraStorageOperationCompleted, userState);
        }
        
        private void OnInsertPurchaseExtraStorageOperationCompleted(object arg) {
            if ((this.InsertPurchaseExtraStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPurchaseExtraStorageCompleted(this, new InsertPurchaseExtraStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserStorageCapacity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserStorageCapacity(ExtraStorageUser ESU) {
            object[] results = this.Invoke("UpdateUserStorageCapacity", new object[] {
                        ESU});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserStorageCapacityAsync(ExtraStorageUser ESU) {
            this.UpdateUserStorageCapacityAsync(ESU, null);
        }
        
        /// <remarks/>
        public void UpdateUserStorageCapacityAsync(ExtraStorageUser ESU, object userState) {
            if ((this.UpdateUserStorageCapacityOperationCompleted == null)) {
                this.UpdateUserStorageCapacityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserStorageCapacityOperationCompleted);
            }
            this.InvokeAsync("UpdateUserStorageCapacity", new object[] {
                        ESU}, this.UpdateUserStorageCapacityOperationCompleted, userState);
        }
        
        private void OnUpdateUserStorageCapacityOperationCompleted(object arg) {
            if ((this.UpdateUserStorageCapacityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserStorageCapacityCompleted(this, new UpdateUserStorageCapacityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private string usernameField;
        
        private string passwordField;
        
        private string typeOfUserField;
        
        private string nameField;
        
        private string emailField;
        
        private string addressField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfUser {
            get {
                return this.typeOfUserField;
            }
            set {
                this.typeOfUserField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtraStorageUser {
        
        private string usernameField;
        
        private string creditCardNumberField;
        
        private string creditCardExpirationField;
        
        private string creditCardCVVField;
        
        private string billingAddressField;
        
        private string phoneNumberField;
        
        private float storageAmountField;
        
        private float storageCostField;
        
        private string nameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardExpiration {
            get {
                return this.creditCardExpirationField;
            }
            set {
                this.creditCardExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardCVV {
            get {
                return this.creditCardCVVField;
            }
            set {
                this.creditCardCVVField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public float StorageAmount {
            get {
                return this.storageAmountField;
            }
            set {
                this.storageAmountField = value;
            }
        }
        
        /// <remarks/>
        public float StorageCost {
            get {
                return this.storageCostField;
            }
            set {
                this.storageCostField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileInfoWS {
        
        private byte[] fileField;
        
        private string fileNameField;
        
        private float fileSizeField;
        
        private string fileTypeField;
        
        private string uploadDateField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public float FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string UploadDate {
            get {
                return this.uploadDateField;
            }
            set {
                this.uploadDateField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConfirmUserLoginCompletedEventHandler(object sender, ConfirmUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AssignWebServiceAPICompletedEventHandler(object sender, AssignWebServiceAPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssignWebServiceAPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssignWebServiceAPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VerifyAPIKeyCompletedEventHandler(object sender, VerifyAPIKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAPIKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAPIKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CloudUserStorageCompletedEventHandler(object sender, CloudUserStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloudUserStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloudUserStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetFilesByUserCompletedEventHandler(object sender, GetFilesByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFilesByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFilesByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteFileCompletedEventHandler(object sender, DeleteFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpDateFileCompletedEventHandler(object sender, UpDateFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpDateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpDateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllUsersCompletedEventHandler(object sender, GetAllUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SelectFilesWithIconsCompletedEventHandler(object sender, SelectFilesWithIconsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectFilesWithIconsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectFilesWithIconsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertUserTransactionsCompletedEventHandler(object sender, InsertUserTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertUserTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertUserTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SelectUserTransactionsCompletedEventHandler(object sender, SelectUserTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUserTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUserTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetFilesByIconCompletedEventHandler(object sender, GetFilesByIconCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFilesByIconCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFilesByIconCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAccountTypeCompletedEventHandler(object sender, GetAccountTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CheckDuplicateUsernameCompletedEventHandler(object sender, CheckDuplicateUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDuplicateUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDuplicateUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetStoragePlansCompletedEventHandler(object sender, GetStoragePlansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoragePlansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoragePlansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertPurchaseExtraStorageCompletedEventHandler(object sender, InsertPurchaseExtraStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPurchaseExtraStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPurchaseExtraStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateUserStorageCapacityCompletedEventHandler(object sender, UpdateUserStorageCapacityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserStorageCapacityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserStorageCapacityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591